.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osInvalDCache, 0xAC

glabel osInvalDCache
    /* 74250 80073650 18A0001F */  blez       $a1, .L800736D0
    /* 74254 80073654 00000000 */   nop
    /* 74258 80073658 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 7425C 8007365C 00AB082B */  sltu       $at, $a1, $t3
    /* 74260 80073660 1020001D */  beqz       $at, .L800736D8
    /* 74264 80073664 00000000 */   nop
    /* 74268 80073668 00804025 */  or         $t0, $a0, $zero
    /* 7426C 8007366C 00854821 */  addu       $t1, $a0, $a1
    /* 74270 80073670 0109082B */  sltu       $at, $t0, $t1
    /* 74274 80073674 10200016 */  beqz       $at, .L800736D0
    /* 74278 80073678 00000000 */   nop
    /* 7427C 8007367C 310A000F */  andi       $t2, $t0, 0xF
    /* 74280 80073680 11400007 */  beqz       $t2, .L800736A0
    /* 74284 80073684 2529FFF0 */   addiu     $t1, $t1, -0x10
    /* 74288 80073688 010A4023 */  subu       $t0, $t0, $t2
    /* 7428C 8007368C BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
    /* 74290 80073690 0109082B */  sltu       $at, $t0, $t1
    /* 74294 80073694 1020000E */  beqz       $at, .L800736D0
    /* 74298 80073698 00000000 */   nop
    /* 7429C 8007369C 25080010 */  addiu      $t0, $t0, 0x10
  .L800736A0:
    /* 742A0 800736A0 312A000F */  andi       $t2, $t1, 0xF
    /* 742A4 800736A4 11400006 */  beqz       $t2, .L800736C0
    /* 742A8 800736A8 00000000 */   nop
    /* 742AC 800736AC 012A4823 */  subu       $t1, $t1, $t2
    /* 742B0 800736B0 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
    /* 742B4 800736B4 0128082B */  sltu       $at, $t1, $t0
    /* 742B8 800736B8 14200005 */  bnez       $at, .L800736D0
    /* 742BC 800736BC 00000000 */   nop
  .L800736C0:
    /* 742C0 800736C0 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
    /* 742C4 800736C4 0109082B */  sltu       $at, $t0, $t1
    /* 742C8 800736C8 1420FFFD */  bnez       $at, .L800736C0
    /* 742CC 800736CC 25080010 */   addiu     $t0, $t0, 0x10
  .L800736D0:
    /* 742D0 800736D0 03E00008 */  jr         $ra
    /* 742D4 800736D4 00000000 */   nop
  .L800736D8:
    /* 742D8 800736D8 3C088000 */  lui        $t0, 0x8000
    /* 742DC 800736DC 010B4821 */  addu       $t1, $t0, $t3
    /* 742E0 800736E0 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800736E4:
    /* 742E4 800736E4 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 742E8 800736E8 0109082B */  sltu       $at, $t0, $t1
    /* 742EC 800736EC 1420FFFD */  bnez       $at, .L800736E4
    /* 742F0 800736F0 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 742F4 800736F4 03E00008 */  jr         $ra
    /* 742F8 800736F8 00000000 */   nop
endlabel osInvalDCache
    /* 742FC 800736FC 00000000 */  nop
