.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osMapTLB, 0xB4

glabel osMapTLB
    /* 73D20 80073120 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 73D24 80073124 40840000 */  mtc0       $a0, $0 /* handwritten instruction */
    /* 73D28 80073128 40852800 */  mtc0       $a1, $5 /* handwritten instruction */
    /* 73D2C 8007312C 8FA90014 */  lw         $t1, 0x14($sp)
    /* 73D30 80073130 2401FFFF */  addiu      $at, $zero, -0x1
    /* 73D34 80073134 11210004 */  beq        $t1, $at, .L80073148
    /* 73D38 80073138 240C0001 */   addiu     $t4, $zero, 0x1
    /* 73D3C 8007313C 240A001E */  addiu      $t2, $zero, 0x1E
    /* 73D40 80073140 10000002 */  b          .L8007314C
    /* 73D44 80073144 00C93025 */   or        $a2, $a2, $t1
  .L80073148:
    /* 73D48 80073148 240A001F */  addiu      $t2, $zero, 0x1F
  .L8007314C:
    /* 73D4C 8007314C 40865000 */  mtc0       $a2, $10 /* handwritten instruction */
    /* 73D50 80073150 2401FFFF */  addiu      $at, $zero, -0x1
    /* 73D54 80073154 10E10006 */  beq        $a3, $at, .L80073170
    /* 73D58 80073158 00000000 */   nop
    /* 73D5C 8007315C 00075982 */  srl        $t3, $a3, 6
    /* 73D60 80073160 016A5825 */  or         $t3, $t3, $t2
    /* 73D64 80073164 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* 73D68 80073168 10000002 */  b          .L80073174
    /* 73D6C 8007316C 00000000 */   nop
  .L80073170:
    /* 73D70 80073170 408C1000 */  mtc0       $t4, $2 /* handwritten instruction */
  .L80073174:
    /* 73D74 80073174 8FAB0010 */  lw         $t3, 0x10($sp)
    /* 73D78 80073178 2401FFFF */  addiu      $at, $zero, -0x1
    /* 73D7C 8007317C 11610006 */  beq        $t3, $at, .L80073198
    /* 73D80 80073180 00000000 */   nop
    /* 73D84 80073184 000B5982 */  srl        $t3, $t3, 6
    /* 73D88 80073188 016A5825 */  or         $t3, $t3, $t2
    /* 73D8C 8007318C 408B1800 */  mtc0       $t3, $3 /* handwritten instruction */
    /* 73D90 80073190 10000007 */  b          .L800731B0
    /* 73D94 80073194 00000000 */   nop
  .L80073198:
    /* 73D98 80073198 408C1800 */  mtc0       $t4, $3 /* handwritten instruction */
    /* 73D9C 8007319C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 73DA0 800731A0 14E10003 */  bne        $a3, $at, .L800731B0
    /* 73DA4 800731A4 00000000 */   nop
    /* 73DA8 800731A8 3C0B8000 */  lui        $t3, (0x80000000 >> 16)
    /* 73DAC 800731AC 408B5000 */  mtc0       $t3, $10 /* handwritten instruction */
  .L800731B0:
    /* 73DB0 800731B0 00000000 */  nop
    /* 73DB4 800731B4 42000002 */  tlbwi /* handwritten instruction */
    /* 73DB8 800731B8 00000000 */  nop
    /* 73DBC 800731BC 00000000 */  nop
    /* 73DC0 800731C0 00000000 */  nop
    /* 73DC4 800731C4 00000000 */  nop
    /* 73DC8 800731C8 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 73DCC 800731CC 03E00008 */  jr         $ra
    /* 73DD0 800731D0 00000000 */   nop
endlabel osMapTLB
    /* 73DD4 800731D4 00000000 */  nop
    /* 73DD8 800731D8 00000000 */  nop
    /* 73DDC 800731DC 00000000 */  nop
