.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osWritebackDCache, 0x74

glabel osWritebackDCache
    /* 741D0 800735D0 18A00011 */  blez       $a1, .L80073618
    /* 741D4 800735D4 00000000 */   nop
    /* 741D8 800735D8 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 741DC 800735DC 00AB082B */  sltu       $at, $a1, $t3
    /* 741E0 800735E0 1020000F */  beqz       $at, .L80073620
    /* 741E4 800735E4 00000000 */   nop
    /* 741E8 800735E8 00804025 */  or         $t0, $a0, $zero
    /* 741EC 800735EC 00854821 */  addu       $t1, $a0, $a1
    /* 741F0 800735F0 0109082B */  sltu       $at, $t0, $t1
    /* 741F4 800735F4 10200008 */  beqz       $at, .L80073618
    /* 741F8 800735F8 00000000 */   nop
    /* 741FC 800735FC 310A000F */  andi       $t2, $t0, 0xF
    /* 74200 80073600 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 74204 80073604 010A4023 */  subu       $t0, $t0, $t2
  .L80073608:
    /* 74208 80073608 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* 7420C 8007360C 0109082B */  sltu       $at, $t0, $t1
    /* 74210 80073610 1420FFFD */  bnez       $at, .L80073608
    /* 74214 80073614 25080010 */   addiu     $t0, $t0, 0x10
  .L80073618:
    /* 74218 80073618 03E00008 */  jr         $ra
    /* 7421C 8007361C 00000000 */   nop
  .L80073620:
    /* 74220 80073620 3C088000 */  lui        $t0, 0x8000
    /* 74224 80073624 010B4821 */  addu       $t1, $t0, $t3
    /* 74228 80073628 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L8007362C:
    /* 7422C 8007362C BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 74230 80073630 0109082B */  sltu       $at, $t0, $t1
    /* 74234 80073634 1420FFFD */  bnez       $at, .L8007362C
    /* 74238 80073638 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 7423C 8007363C 03E00008 */  jr         $ra
    /* 74240 80073640 00000000 */   nop
endlabel osWritebackDCache
    /* 74244 80073644 00000000 */  nop
    /* 74248 80073648 00000000 */  nop
    /* 7424C 8007364C 00000000 */  nop
