.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching zjSetVec, 0x18

glabel zjSetVec
    /* 72B40 80071F40 3C088009 */  lui        $t0, %hi(gSecureCallArr)
    /* 72B44 80071F44 25085880 */  addiu      $t0, $t0, %lo(gSecureCallArr)
    /* 72B48 80071F48 00044880 */  sll        $t1, $a0, 2
    /* 72B4C 80071F4C 01094021 */  addu       $t0, $t0, $t1
    /* 72B50 80071F50 03E00008 */  jr         $ra
    /* 72B54 80071F54 AD050000 */   sw        $a1, 0x0($t0)
endlabel zjSetVec
    /* 72B58 80071F58 00000000 */  nop
    /* 72B5C 80071F5C 00000000 */  nop
