.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching setwatch, 0x20

glabel setwatch
    /* 72B10 80071F10 3C097FFF */  lui        $t1, (0x7FFFFFF8 >> 16)
    /* 72B14 80071F14 3529FFF8 */  ori        $t1, $t1, (0x7FFFFFF8 & 0xFFFF)
    /* 72B18 80071F18 00804025 */  or         $t0, $a0, $zero
    /* 72B1C 80071F1C 01094024 */  and        $t0, $t0, $t1
    /* 72B20 80071F20 35080001 */  ori        $t0, $t0, 0x1
    /* 72B24 80071F24 40889000 */  mtc0       $t0, $18 /* handwritten instruction */
    /* 72B28 80071F28 03E00008 */  jr         $ra
    /* 72B2C 80071F2C 00000000 */   nop
endlabel setwatch

/* Handwritten function */
nonmatching resetwatch, 0x10

glabel resetwatch
    /* 72B30 80071F30 00004025 */  or         $t0, $zero, $zero
    /* 72B34 80071F34 40889000 */  mtc0       $t0, $18 /* handwritten instruction */
    /* 72B38 80071F38 03E00008 */  jr         $ra
    /* 72B3C 80071F3C 00000000 */   nop
endlabel resetwatch
