.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osSetIntMask, 0xA0

glabel osSetIntMask
    /* 74B20 80073F20 400C6000 */  mfc0       $t4, $12 /* handwritten instruction */
    /* 74B24 80073F24 3182FF01 */  andi       $v0, $t4, 0xFF01
    /* 74B28 80073F28 3C088009 */  lui        $t0, %hi(D_80091CA0)
    /* 74B2C 80073F2C 25081CA0 */  addiu      $t0, $t0, %lo(D_80091CA0)
    /* 74B30 80073F30 8D0B0000 */  lw         $t3, 0x0($t0)
    /* 74B34 80073F34 2401FFFF */  addiu      $at, $zero, -0x1
    /* 74B38 80073F38 01614026 */  xor        $t0, $t3, $at
    /* 74B3C 80073F3C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 74B40 80073F40 00481025 */  or         $v0, $v0, $t0
    /* 74B44 80073F44 3C0AA430 */  lui        $t2, %hi(D_A430000C)
    /* 74B48 80073F48 8D4A000C */  lw         $t2, %lo(D_A430000C)($t2)
    /* 74B4C 80073F4C 11400005 */  beqz       $t2, .L80073F64
    /* 74B50 80073F50 000B4C02 */   srl       $t1, $t3, 16
    /* 74B54 80073F54 2401FFFF */  addiu      $at, $zero, -0x1
    /* 74B58 80073F58 01214826 */  xor        $t1, $t1, $at
    /* 74B5C 80073F5C 3129003F */  andi       $t1, $t1, 0x3F
    /* 74B60 80073F60 01495025 */  or         $t2, $t2, $t1
  .L80073F64:
    /* 74B64 80073F64 000A5400 */  sll        $t2, $t2, 16
    /* 74B68 80073F68 004A1025 */  or         $v0, $v0, $t2
    /* 74B6C 80073F6C 3C01003F */  lui        $at, (0x3F0000 >> 16)
    /* 74B70 80073F70 00814024 */  and        $t0, $a0, $at
    /* 74B74 80073F74 010B4024 */  and        $t0, $t0, $t3
    /* 74B78 80073F78 000843C2 */  srl        $t0, $t0, 15
    /* 74B7C 80073F7C 3C0A8009 */  lui        $t2, %hi(D_80094520)
    /* 74B80 80073F80 01485021 */  addu       $t2, $t2, $t0
    /* 74B84 80073F84 954A4520 */  lhu        $t2, %lo(D_80094520)($t2)
    /* 74B88 80073F88 3C01A430 */  lui        $at, %hi(D_A430000C)
    /* 74B8C 80073F8C AC2A000C */  sw         $t2, %lo(D_A430000C)($at)
    /* 74B90 80073F90 3088FF01 */  andi       $t0, $a0, 0xFF01
    /* 74B94 80073F94 3169FF00 */  andi       $t1, $t3, 0xFF00
    /* 74B98 80073F98 01094024 */  and        $t0, $t0, $t1
    /* 74B9C 80073F9C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 74BA0 80073FA0 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 74BA4 80073FA4 01816024 */  and        $t4, $t4, $at
    /* 74BA8 80073FA8 01886025 */  or         $t4, $t4, $t0
    /* 74BAC 80073FAC 408C6000 */  mtc0       $t4, $12 /* handwritten instruction */
    /* 74BB0 80073FB0 00000000 */  nop
    /* 74BB4 80073FB4 00000000 */  nop
    /* 74BB8 80073FB8 03E00008 */  jr         $ra
    /* 74BBC 80073FBC 00000000 */   nop
endlabel osSetIntMask
