.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osUnmapTLBAll, 0x44

glabel osUnmapTLBAll
    /* 75080 80074480 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 75084 80074484 2409001E */  addiu      $t1, $zero, 0x1E
    /* 75088 80074488 3C0A8000 */  lui        $t2, (0x80000000 >> 16)
    /* 7508C 8007448C 408A5000 */  mtc0       $t2, $10 /* handwritten instruction */
    /* 75090 80074490 40801000 */  mtc0       $zero, $2 /* handwritten instruction */
    /* 75094 80074494 40801800 */  mtc0       $zero, $3 /* handwritten instruction */
  .L80074498:
    /* 75098 80074498 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 7509C 8007449C 00000000 */  nop
    /* 750A0 800744A0 42000002 */  tlbwi /* handwritten instruction */
    /* 750A4 800744A4 00000000 */  nop
    /* 750A8 800744A8 00000000 */  nop
    /* 750AC 800744AC 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* 750B0 800744B0 0521FFF9 */  bgez       $t1, .L80074498
    /* 750B4 800744B4 00000000 */   nop
    /* 750B8 800744B8 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 750BC 800744BC 03E00008 */  jr         $ra
    /* 750C0 800744C0 00000000 */   nop
endlabel osUnmapTLBAll
    /* 750C4 800744C4 00000000 */  nop
    /* 750C8 800744C8 00000000 */  nop
    /* 750CC 800744CC 00000000 */  nop
