.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

/* Handwritten function */
nonmatching osWritebackDCacheAll, 0x28

glabel osWritebackDCacheAll
    /* 74D10 80074110 3C088000 */  lui        $t0, 0x8000
    /* 74D14 80074114 240A2000 */  addiu      $t2, $zero, 0x2000
    /* 74D18 80074118 010A4821 */  addu       $t1, $t0, $t2
    /* 74D1C 8007411C 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L80074120:
    /* 74D20 80074120 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 74D24 80074124 0109082B */  sltu       $at, $t0, $t1
    /* 74D28 80074128 1420FFFD */  bnez       $at, .L80074120
    /* 74D2C 8007412C 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 74D30 80074130 03E00008 */  jr         $ra
    /* 74D34 80074134 00000000 */   nop
endlabel osWritebackDCacheAll
    /* 74D38 80074138 00000000 */  nop
    /* 74D3C 8007413C 00000000 */  nop
